markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true

permalink: pretty
source: docs

# Local development
# baseurl: ""
# url: "" # the base hostname & protocol for your site

# Publish
baseurl: "http://greendius.github.io/wattanee"
url: "http://greendius.github.io/wattanee" # the base hostname & protocol for your site

version: 0.0.0

sass:
  sass_dir: ../
  style: compressed

github:
  repo: http://greendius.github.io/wattanee/
